openapi: 3.0.3
tags:
  - name: SenderReadB2B
    description: >-
      Invocazioni utilizzabili dai mittenti per verificare lo stato delle richieste 
      di notifica inviate e delle notifiche accettate.
paths:
  # Implementata con una lambda utilizzando il meccanismo che sta preparando Fabrizio D.
  #  con la issue PN-7255
  "/delivery/notifications/sent/{iun}":
    get:
      summary: 'Mittente: lettura dettagli notifica'
      description: |-
        Questa operazione permette di leggere tutti i dettagli di una notifica accettata. <br/>

        <details no-external>
        <summary><b> Attributi progettazione di alto livello </b></summary>
        | Proprietà                | Valore             |
        | -----------------------: | :----------------- |
        | __Intended usage__       | B2B, WEB           |
        | __Modalità interazione__ | Sincrona           |
        | __TPS (stimato)__        |                    |
        | __Idempotenza__          | Si                 |
        | __Read/Write intensive__ | Read               |
        | __Cachable__             | No                 |
        </details>
      tags:
        - SenderReadB2B
      operationId: getSentNotification                                      # NO EXTERNAL
#      operationId: retrieveSentNotification                                # ONLY EXTERNAL
      x-pagopa-lambda-name: ilNomeDellaLambda
      x-pagopa-lambda-account: core
      parameters:
        - $ref: '#/components/parameters/uidAuthFleet'            # NO EXTERNAL
        - $ref: '#/components/parameters/cxTypeAuthFleet'         # NO EXTERNAL
        - $ref: '#/components/parameters/cxIdAuthFleet'           # NO EXTERNAL
        - $ref: '#/components/parameters/cxGroupsAuthFleet'       # NO EXTERNAL
        - $ref: './parameters-notification-search.yaml#/components/parameters/pathIun'
      responses:
        '200':
          description: OK
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/FullSentNotification"
        '400':
          description: Bad request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '500':
          description: Internal error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
  

components:  

  parameters:

    ############################################################################################
    ###                     PARAMETRI DI AUTENTICAZIONE E AUTORIZZAZIONE                     ###
    ############################################################################################
    cxTypeAuthFleet:                                                                # NO EXTERNAL
      $ref: './remote-refs.yaml#/components/parameters/cxTypeAuthFleet'             # NO EXTERNAL
    cxIdAuthFleet:                                                                  # NO EXTERNAL
      $ref: './remote-refs.yaml#/components/parameters/cxIdAuthFleet'               # NO EXTERNAL
    cxGroupsAuthFleet:                                                              # NO EXTERNAL
      $ref: './remote-refs.yaml#/components/parameters/cxGroupsAuthFleet'           # NO EXTERNAL
    uidAuthFleet:                                                                   # NO EXTERNAL
      $ref: './remote-refs.yaml#/components/parameters/uidAuthFleet'                # NO EXTERNAL

  schemas:

    ###########################################################################################
    ###                             DTO STATUS PN                                           ###
    ###########################################################################################
    PnStatusResponse:
      $ref: './remote-refs.yaml#/components/schemas/PnStatusResponse'

    FullSentNotification:
      description: >-
        Le informazioni riguardanti una notifica (richiesta di notifica accettata) e il 
        processo di inoltro della notifica verso il cittadino.
      allOf:
        - $ref: './schemas-pn-notification.yaml#/components/schemas/SentNotification'
        - type: object
          required:
            - notificationStatus
            - notificationStatusHistory
            - timeline
          properties:
            notificationStatus:
              $ref: '#/components/schemas/NotificationStatus'
            notificationStatusHistory:
              $ref: '#/components/schemas/NotificationStatusHistory'
            timeline:
              description: >-
                elenco dettagliato di tutto ciò che è accaduto durrante il processo di notifica
              type: array
              items:
                $ref: '#/components/schemas/TimelineElement'
            recipientIds:                                                               # NO EXTERNAL
              description: Lista degli identificativi anonimizzati dei destinatari      # NO EXTERNAL
              type: array                                                               # NO EXTERNAL
              items:                                                                    # NO EXTERNAL
                type: string                                                            # NO EXTERNAL
            sourceChannel:                                                              # NO EXTERNAL
              type: string                                                              # NO EXTERNAL
              description: Canale sorgente della richiesta di notifica                  # NO EXTERNAL
            sourceChannelDetails:                                                       # NO EXTERNAL
              type: string                                                              # NO EXTERNAL
              description: Dettagli del canale sorgente della richiesta di notifica     # NO EXTERNAL
        
    TimelineElement:
      $ref: './remote-refs.yaml#/components/schemas/TimelineElement'
    NotificationStatus:
      $ref: './remote-refs.yaml#/components/schemas/NotificationStatus'
    NotificationStatusHistory:
      $ref: './remote-refs.yaml#/components/schemas/NotificationStatusHistory'
    
    Problem:
      $ref: './remote-refs.yaml#/components/schemas/Problem'
    ProblemError:
      $ref: './remote-refs.yaml#/components/schemas/ProblemError'
