# di seguito le variabili che possono subire variazioni in caso di modifiche all'applicazione, da ricercare in base all'ID
# <span id="pnTemporaryDocument">7 giorni</span> configurazione per file temporanei caricati prima dell'inserimento notifica, definito in storageConfigurations name: PN_TEMPORARY_DOCUMENT in pn-safestorage-v1-api.yaml
# <span id="numberOfPresignedRequest">15</span> pn.delivery.number-of-presigned-request=15 numero di maxItems della preloadRequest
openapi: 3.0.3

paths:
  "/delivery/cost/{iun}/recipient/{recIndex}":
    get:
      operationId: NotificationCostRecipient                                     # ONLY EXTERNAL
      summary: Retrieve notification cost for recipient
      description: >-
        Servizio che restituisce il costo di notificazione per il singolo destinatario
      tags:
        - NotificationCostRecipient
      parameters:
        - $ref: './parameters-notification-search.yaml#/components/parameters/pathIun'
        - name: recIndex
          in: path
          required: true
          example: '0'
          type: integer
          description: Index destinatario notifica digitale
          format: int32
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotificationCostRecipientResponse'
        '400':
          description: Invalid input
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '404':
          description: Not Found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '500':
          description: Internal Server Error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'


components:

  schemas:
    NotificationCostRecipientResponse:
      title: Notification cost Response for recipient
      description: >-
        Notification cost and effective date
      type: object
      properties:
        totalCost:
          $ref: '#/components/schemas/TotalCost'
        pagoPaIntMode:
          type: string
          description: >-
            Modalitá di integrazione pagoPA per l'attualizazione del costo della notifica. <br/>
            - _NONE_: nessuna attualizzazione. <br/>
            - _SYNC_: modalitá sincrona. <br/>
            - _ASYNC_: modalitá asincrona. <br/>
          enum:
            - NONE
            - SYNC
            - ASYNC

    PaFee:
      type: integer
      description: >-
        Costo espresso in eurocent sostenuto dal mittente, per l'elaborazione degli
        atti, provvedimenti, avvisi e comunicazioni oggetto di notifica, per
        il relativo deposito sulla piattaforma e per la gestione degli  esiti
        della notifica (Decreto 30 maggio 2022 - Art. 3, comma 1, lettera a). <br/>
        Obbligatoria per notifiche con notificationFeePolicy=DELIVERY_MODE <br/>
        Per le notifiche effettuate con versioni precedenti alla 2.3 si assume il valore di default 100.<br/>
        Esempio paFee ad 1€ -> 100 <br/>
      format: int32
      minimum: 0
      maximum: 100

    TotalCost:
      title: Costo totale di notificazione applicato all'utente
      description: >-
        ----
      type: object
      properties:
        cost:
          description: Costo totale in eurocent
          type: integer
          format: int32
        details:
          $ref: '#/components/schemas/TotalCostDetails'

    TotalCostDetails:
      title: Dettaglio del costo totale
      description: >-
        ----
      type: object
      properties:
        baseCost:
          $ref: '#/components/schemas/BaseCost'
        firstAnalogCost:
          $ref: '#/components/schemas/AnalogCost'
        secondAnalogCost:
          $ref: '#/components/schemas/AnalogCost'
        vat:
          type: integer
          description: >-
            IVA espressa in percentuale sui costi degli avvisi in formato cartaceo.<br/>
            Esempio vat al 22% -> 22 <br/>
          format: int32
          minimum: 0
          maximum: 100
        notificationFeePolicy:
          type: string
          description: >-
            Politica di addebitamento dei costi di notifica. <br/>
            - _FLAT_RATE_: costo forfettario fisso. In questa modalità SEND non gestisce 
            il costo della notifica per il destinatario.<br/>
            - _DELIVERY_MODE_: costo calcolato in base all'effettivo percorso di notifica. <br/>
          enum:
            - FLAT_RATE
            - DELIVERY_MODE

    BaseCost:
      title: Costo totale di notificazione applicato all'utente
      description: >-
        ----
      type: object
      properties:
        cost:
          description: Costo base di notificazione in eurocent, dato da paFee e sendFee
          type: integer
          format: int32
        details:
          $ref: '#/components/schemas/BaseCostDetails'

    BaseCostDetails:
      title: Dettaglio del costo base di notificazione
      description: >-
        ----
      type: object
      properties:
        paFee:
          type: integer
          description: >-
            Costo espresso in eurocent sostenuto dal mittente
            Esempio paFee ad 1€ -> 100 <br/>
          format: int32
          minimum: 0
          maximum: 100
        sendFee:
          description: costo base di SeND per notificazione
          type: integer
          format: int32

    AnalogCost:
      title: Costo di invio cartaceo
      description: >-
        Costo del singolo invio cartaceo compreso di iva (vat), con il dettaglio sul tipo di prodotto
      type: object
      properties:
        cost:
          description: Costo invio cartaceo in eurocent compreso di iva (vat)
          type: integer
          format: int32
        productType:
          type: string
          maxLength: 10
          description: >
            Tipo di invio cartaceo effettivamente inviato
              - __AR__: Raccomandata nazionale Andata e Ritorno
              - __890__: Recapito a norma della legge 890/1982
              - __RIR__: Raccomandata internazionale Andata e Ritorno
              - __RS__: Raccomandata nazionale Semplice
              - __RIS__: Raccomandata internazionale Semplice

    Problem:
      $ref: './remote-refs.yaml#/components/schemas/Problem'
    ProblemError:
      $ref: './remote-refs.yaml#/components/schemas/ProblemError'




