# di seguito le variabili che possono subire variazioni in caso di modifiche all'applicazione, da ricercare in base all'ID
# <span id="pnTemporaryDocument">7 giorni</span> configurazione per file temporanei caricati prima dell'inserimento notifica, definito in storageConfigurations name: PN_TEMPORARY_DOCUMENT in pn-safestorage-v1-api.yaml
# <span id="numberOfPresignedRequest">15</span> pn.delivery.number-of-presigned-request=15 numero di maxItems della preloadRequest
openapi: 3.0.3

paths:
  "/delivery/price/{iun}/recipient/{recIndex}":
    get:
      operationId: NotificationPriceRecipient                                     # ONLY EXTERNAL
      summary: Retrieve notification price for recipient
      description: >-
        Servizio che restituisce il costo di notificazione per il singolo destinatario
      tags:
        - NotificationPriceRecipient
      parameters:
        - $ref: './parameters-notification-search.yaml#/components/parameters/pathIun'
        - name: recIndex
          in: path
          required: true
          example: '0'
          type: integer
          description: Index destinatario notifica digitale
          format: int32
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotificationPriceResponseV23'
        '400':
          description: Invalid input
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '404':
          description: Not Found
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '500':
          description: Internal Server Error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'


components:

  schemas:
    NotificationPriceRecipientResponse:
      title: Notification price Response for recipient
      description: >-
        Notification price and effective date
      type: object
      properties:
        totalPrice:
          description:
            Costo totale di notificazione in eurocent, che include la paFee e vat applicato ai costi cartacei
          type: integer
          format: int32
        baseCost:
            description: Costo base di notificazione in eurocent, dato da paFee e sendFee
            type: integer
            format: int32
        firstAnalogCost:
          $ref: '#/components/schemas/AnalogCost'
        secondAnalogCost:
          $ref: '#/components/schemas/AnalogCost'
        vat:
          $ref: 'schemas-pn-notification.yaml#/components/schemas/VatV23'
        paFee:
          $ref: 'schemas-pn-notification.yaml#/components/schemas/PaFeeV23'
        sendFee:
          description: costo base di SeND per notificazione
          type: integer
          format: int32
        notificationFeePolicy:
          $ref: './schemas-pn-notification.yaml#/components/schemas/NotificationFeePolicy'
        pagoPaIntMode:
          type: string
          description: >-
            Modalitá di integrazione pagoPA per l'attualizazione del costo della notifica. <br/>
            - _NONE_: nessuna attualizzazione. <br/>
            - _SYNC_: modalitá sincrona. <br/>
            - _ASYNC_: modalitá asincrona. <br/>
          enum:
            - NONE
            - SYNC
            - ASYNC

    AnalogCost:
      title: Costo di invio cartaceo
      description: >-
        Costo del singolo invio cartaceo compreso di iva (vat), con il dettaglio sul tipo di prodotto
      type: object
      properties:
        cost:
          description: Costo invio cartaceo in eurocent compreso di iva (vat)
          type: integer
          format: int32
        productType:
          type: string
          maxLength: 10
          description: >
            Tipo di invio cartaceo effettivamente inviato
              - __AR__: Raccomandata nazionale Andata e Ritorno
              - __890__: Recapito a norma della legge 890/1982
              - __RIR__: Raccomandata internazionale Andata e Ritorno
              - __RS__: Raccomandata nazionale Semplice
              - __RIS__: Raccomandata internazionale Semplice

    Problem:
      $ref: './remote-refs.yaml#/components/schemas/Problem'
    ProblemError:
      $ref: './remote-refs.yaml#/components/schemas/ProblemError'




