AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy PN-delivery and ensure infrastructure

Resources:
  Keyspace:
    Type: AWS::Cassandra::Keyspace
    Properties:
      KeyspaceName: TestKeySpace

  NotificationIunTable:
    Type: AWS::Cassandra::Table
    Properties:
      TableName: iun_cluster_by_senderid
      KeyspaceName: TestKeySpace
      PointInTimeRecoveryEnabled: true
      PartitionKeyColumns:
        - ColumnName: notificationstatus
          ColumnType: text
        - ColumnName: senderid
          ColumnType: text
      ClusteringKeyColumns:
        - Column:
            ColumnName: sentat
            ColumnType: timestamp
          OrderBy: ASC
        - Column:
            ColumnName: recipientid
            ColumnType: text
          OrderBy: ASC
        - Column:
            ColumnName: iun
            ColumnType: text
          OrderBy: ASC
      RegularColumns:
        - ColumnName: panotificationid
          ColumnType: text
        - ColumnName: subject
          ColumnType: text
        - ColumnName: recipientsjson
          ColumnType: map<text, text>