AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy PN-delivery and ensure infrastructure

Parameters:
  EnvName:
    Type: String
    Description: Nome dell'ambiente destinazione
  EnvNumber:
    Type: String
    Description: Second byte from the left for VPC CIDR
  KeyspaceName:
    Type: String
    Description: cassandra keyspace name

Resources:
  Cluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Join [ '', [ !Ref EnvName, DeliveryCluster ] ]
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    # Makes sure the log group is created before it is used.
    DependsOn: LogGroup
    Properties:
      # Name of the task definition. Subsequent versions of the task definition are grouped together under this name.
      Family: !Join [ '', [ !Ref EnvName, DeliveryTaskDefinition ] ]
      # awsvpc is required for Fargate
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      # 256 (.25 vCPU) - Available memory values: 0.5GB, 1GB, 2GB
      # 512 (.5 vCPU) - Available memory values: 1GB, 2GB, 3GB, 4GB
      # 1024 (1 vCPU) - Available memory values: 2GB, 3GB, 4GB, 5GB, 6GB, 7GB, 8GB
      # 2048 (2 vCPU) - Available memory values: Between 4GB and 16GB in 1GB increments
      # 4096 (4 vCPU) - Available memory values: Between 8GB and 30GB in 1GB increments
      Cpu: 1024
      # 0.5GB, 1GB, 2GB - Available cpu values: 256 (.25 vCPU)
      # 1GB, 2GB, 3GB, 4GB - Available cpu values: 512 (.5 vCPU)
      # 2GB, 3GB, 4GB, 5GB, 6GB, 7GB, 8GB - Available cpu values: 1024 (1 vCPU)
      # Between 4GB and 16GB in 1GB increments - Available cpu values: 2048 (2 vCPU)
      # Between 8GB and 30GB in 1GB increments - Available cpu values: 4096 (4 vCPU)
      Memory: 2GB
      # A role needed by ECS.
      # "The ARN of the task execution role that containers in this task can assume. All containers in this task are granted the permissions that are specified in this role."
      # "There is an optional task execution IAM role that you can specify with Fargate to allow your Fargate tasks to make API calls to Amazon ECR."
      ExecutionRoleArn: !Ref ExecutionRole
      # "The Amazon Resource Name (ARN) of an AWS Identity and Access Management (IAM) role that grants containers in the task permission to call AWS APIs on your behalf."
      TaskRoleArn: !Ref TaskRole
      ContainerDefinitions:
        - Name: !Sub '${EnvName}-delivery'
          Image: !Sub '${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${EnvName}-pn-delivery:latest'
          Environment:
            - Name: AWS_REGIONCODE
              Value: !Ref AWS::Region
            - Name: PN_DELIVERY_TOPICS_NEWNOTIFICATIONS
              Value: !ImportValue { "Fn::Sub": '${EnvName}-delpush-input-queue-name' }
            - Name: AWS_BUCKETNAME
              Value: !ImportValue { "Fn::Sub": '${EnvName}-attachments-bucket-name' }
            - Name: PN_DELIVERY_IUNRETRY
              Value: 3
            - Name: SPRING_DATA_CASSANDRA_KEYSPACENAME
              Value: !Sub ${Keyspace}
            - Name: SPRING_DATA_CASSANDRA_SSL
              Value: true
            - Name: SPRING_DATA_CASSANDRA_CONTACTPOINTS
              Value: !Sub 'cassandra.${AWS::Region}.${AWS::URLSuffix}:9142'
          PortMappings:
            - ContainerPort: 8080
          # Send logs to CloudWatch Logs
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-region: !Ref AWS::Region
              awslogs-group: !Ref LogGroup
              awslogs-stream-prefix: ecs
  # A role needed by ECS
  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Join [ '', [ !Ref EnvName, DeliveryExecutionRole ] ]
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy'
  # A role for the containers
  TaskRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Join [ '', [ !Ref EnvName, DeliveryTaskRole ] ]
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: 'sts:AssumeRole'
  TaskPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub ${EnvName}-inst-delivery-policy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - sqs:ChangeMessageVisibility
              - sqs:ChangeMessageVisibilityBatch
              - sqs:DeleteMessage
              - sqs:DeleteMessageBatch
              - sqs:GetQueueAttributes
              - sqs:GetQueueUrl
              - sqs:ReceiveMessage
              - sqs:SendMessage
              - sqs:SendMessageBatch
            Resource:
              - !ImportValue { "Fn::Sub": '${EnvName}-delpush-input-queue-arn' }
              - !ImportValue { "Fn::Sub": '${EnvName}-extchannel-input-queue-arn' }
          - Effect: Allow
            Action:
              - s3:GetObject
              - s3:GetObjectAcl
              - s3:GetObjectLegalHold
              - s3:GetObjectRetention
              - s3:GetObjectTagging
              - s3:GetObjectVersion
              - s3:GetObjectVersionAcl
              - s3:GetObjectVersionTagging
              - s3:PutObject
              - s3:PutObjectLegalHold
              - s3:PutObjectRetention
              - s3:PutObjectTagging
              - s3:PutObjectVersionTagging
            Resource:
              - !Join
                - '/'
                - - !ImportValue { "Fn::Sub": '${EnvName}-attachments-bucket-arn' }
                  - '*'
          - Effect: Allow
            Action:
              - s3:ListBucket
            Resource:
              - !ImportValue { "Fn::Sub": '${EnvName}-attachments-bucket-arn' }
          - Effect: Allow
            Action:
              - cassandra:Modify
              - cassandra:Select
            Resource:
              - !Sub "arn:aws:cassandra:*:${AWS::AccountId}:/keyspace/*/table/*"
      Roles:
        - !Ref TaskRole
  # A role needed for auto scaling
  AutoScalingRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Join [ '', [ !Ref EnvName, DeliveryAutoScalingRole ] ]
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceAutoscaleRole'
  ContainerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Join [ '', [ !Ref EnvName, DeliveryContSecGrp ] ]
      VpcId: !ImportValue
        "Fn::Sub": '${EnvName}-vpc-id'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0
          #SourceSecurityGroupId: !Ref LoadBalancerSecurityGroup
  LoadBalancerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Join [ '', [ !Ref EnvName, DeliveryLbSecGrp ] ]
      VpcId: !ImportValue
        "Fn::Sub": '${EnvName}-vpc-id'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0
  DeliveryService:
    Type: AWS::ECS::Service
    # This dependency is needed so that the load balancer is setup correctly in time
    #DependsOn:
    #  - ListenerHTTP
    Properties:
      #ServiceName: !Sub '${EnvName}-delivery'
      Cluster: !Ref Cluster
      TaskDefinition: !Ref TaskDefinition
      DeploymentConfiguration:
        MinimumHealthyPercent: 100
        MaximumPercent: 200
      DesiredCount: 1
      # This may need to be adjusted if the container takes a while to start up
      #HealthCheckGracePeriodSeconds: 30
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          # change to DISABLED if you're using private subnets that have access to a NAT gateway
          AssignPublicIp: ENABLED
          Subnets:
            - !ImportValue { "Fn::Sub": '${EnvName}-subnet1' }
            - !ImportValue { "Fn::Sub": '${EnvName}-subnet2' }
          SecurityGroups:
            - !Ref ContainerSecurityGroup
      LoadBalancers:
        - ContainerName: !Sub '${EnvName}-delivery'
          ContainerPort: 8080
          TargetGroupArn: !Ref DeliveryTargetGroup
        - ContainerName: !Sub '${EnvName}-delivery'
          ContainerPort: 8080
          TargetGroupArn: !Ref DeliveryNetTargetGroup

  DeliveryTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      #Name: !Sub ${EnvName}-delivery-tgrp
      TargetType: ip
      Protocol: HTTP
      Port: 8080
      HealthCheckEnabled: true
      HealthCheckIntervalSeconds: 10
      HealthCheckPath: /
      HealthCheckPort: 8080
      HealthCheckProtocol: HTTP
      Matcher:
        HttpCode: 303
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: 60 # default is 300
      VpcId: !ImportValue
        "Fn::Sub": '${EnvName}-vpc-id'
  DeliveryLoadBalancerListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !ImportValue
        "Fn::Sub": '${EnvName}-alb-id'
      Protocol: HTTP
      Port: 8080
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref DeliveryTargetGroup
          Order: 1

  DeliveryNetTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      #Name: !Sub ${EnvName}-delivery-nlb-tg
      TargetType: ip
      Protocol: TCP
      Port: 8080
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: 60 # default is 300
      VpcId: !ImportValue
        "Fn::Sub": '${EnvName}-vpc-id'
  DeliveryNetLoadBalancerListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !ImportValue
        "Fn::Sub": '${EnvName}-nlb-id'
      Protocol: TCP
      Port: 8080
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref DeliveryNetTargetGroup
          Order: 1

  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Join [ '', [ /ecs/, !Ref EnvName, Delivery ] ]
      RetentionInDays: 3
  AutoScalingTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    Properties:
      MinCapacity: 1
      MaxCapacity: 1
      ResourceId: !Join [ '/', [ service, !Ref Cluster, !GetAtt DeliveryService.Name ] ]
      ScalableDimension: ecs:service:DesiredCount
      ServiceNamespace: ecs
      # "The Amazon Resource Name (ARN) of an AWS Identity and Access Management (IAM) role that allows Application Auto Scaling to modify your scalable target."
      RoleARN: !GetAtt AutoScalingRole.Arn
  AutoScalingPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: !Join [ '', [ !Ref EnvName, DeliveryAutoScalingPolicy ] ]
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref AutoScalingTarget
      TargetTrackingScalingPolicyConfiguration:
        PredefinedMetricSpecification:
          PredefinedMetricType: ECSServiceAverageCPUUtilization
        ScaleInCooldown: 10
        ScaleOutCooldown: 10
        # Keep things at or lower than 50% CPU utilization, for example
        TargetValue: 60
  
  Keyspace:
    Type: AWS::Cassandra::Keyspace
    Properties:
      KeyspaceName: !Ref KeyspaceName

  NotificationTable:
    Type: AWS::Cassandra::Table
    Properties:
      TableName: notifications
      KeyspaceName: !Ref Keyspace
      PointInTimeRecoveryEnabled: true
      PartitionKeyColumns:
        - ColumnName: iun
          ColumnType: text
      RegularColumns:
        - ColumnName: cancelledbyiun
          ColumnType: text
        - ColumnName: cancellediun
          ColumnType: text
        - ColumnName: panotificationid
          ColumnType: text
        - ColumnName: subject
          ColumnType: text
        - ColumnName: senderpaid
          ColumnType: text
        - ColumnName: sentat
          ColumnType: timestamp
        - ColumnName: recipientsjson
          ColumnType: map<text, text>
        - ColumnName: recipientsorder
          ColumnType: list<text>
        - ColumnName: documentskeys
          ColumnType: list<text>
        - ColumnName: documentsdigestssha256
          ColumnType: list<text>
        - ColumnName: documentsversionids
          ColumnType: list<text>
        - ColumnName: iuv
          ColumnType: text
        - ColumnName: notificationfeepolicy
          ColumnType: text
        - ColumnName: f24flatratekey
          ColumnType: text
        - ColumnName: f24flatratedigestsha256
          ColumnType: text
        - ColumnName: f24flatrateversionid
          ColumnType: text
        - ColumnName: f24digitalkey
          ColumnType: text
        - ColumnName: f24digitaldigestsha256
          ColumnType: text
        - ColumnName: f24digitalversionid
          ColumnType: text
        - ColumnName: f24analogkey
          ColumnType: text
        - ColumnName: f24analogdigestsha256
          ColumnType: text
        - ColumnName: f24analogversionid
          ColumnType: text
        - ColumnName: physical_communication_type
          ColumnType: text

  TimelineTable:
    Type: AWS::Cassandra::Table
    Properties:
      TableName: timelines
      KeyspaceName: !Ref Keyspace
      PointInTimeRecoveryEnabled: true
      PartitionKeyColumns:
        - ColumnName: iun
          ColumnType: text
      ClusteringKeyColumns:
        - Column:
            ColumnName: timeline_element_id
            ColumnType: text
          OrderBy: ASC
      RegularColumns:
        - ColumnName: category
          ColumnType: text
        - ColumnName: details
          ColumnType: text
        - ColumnName: timestamp
          ColumnType: timestamp

  NotificationBySenderTable:
    Type: AWS::Cassandra::Table
    Properties:
      TableName: iun_by_senderid
      KeyspaceName: !Ref Keyspace
      PointInTimeRecoveryEnabled: true
      PartitionKeyColumns:
        - ColumnName: notificationstatus
          ColumnType: text
        - ColumnName: senderid
          ColumnType: text
      ClusteringKeyColumns:
        - Column:
            ColumnName: sentat
            ColumnType: timestamp
          OrderBy: DESC
        - Column:
            ColumnName: recipientid
            ColumnType: text
          OrderBy: ASC
        - Column:
            ColumnName: iun
            ColumnType: text
          OrderBy: ASC
      RegularColumns:
        - ColumnName: panotificationid
          ColumnType: text
        - ColumnName: subject
          ColumnType: text
        - ColumnName: recipientsjson
          ColumnType: map<text, text>

  NotificationByReceiverTable:
    Type: AWS::Cassandra::Table
    Properties:
      TableName: iun_by_recipientid
      KeyspaceName: !Ref Keyspace
      PointInTimeRecoveryEnabled: true
      PartitionKeyColumns:
        - ColumnName: notificationstatus
          ColumnType: text
        - ColumnName: recipientid
          ColumnType: text
      ClusteringKeyColumns:
        - Column:
            ColumnName: sentat
            ColumnType: timestamp
          OrderBy: DESC
        - Column:
            ColumnName: senderid
            ColumnType: text
          OrderBy: ASC
        - Column:
            ColumnName: iun
            ColumnType: text
          OrderBy: ASC
      RegularColumns:
        - ColumnName: panotificationid
          ColumnType: text
        - ColumnName: subject
          ColumnType: text
        - ColumnName: recipientsjson
          ColumnType: map<text, text>

  DirectAccessTokenTable:
    Type: AWS::Cassandra::Table
    Properties:
      TableName: direct_access_tokens
      KeyspaceName: !Ref Keyspace
      PointInTimeRecoveryEnabled: true
      PartitionKeyColumns:
        - ColumnName: token
          ColumnType: text
      RegularColumns:
        - ColumnName: iun
          ColumnType: text
        - ColumnName: taxid
          ColumnType: text

Outputs:
  CluserArn:
    Description: ARN del cluster fargate
    Value: !Sub '${Cluster.Arn}'
  ServiceName:
    Description: Nome del servizio di cui fare deploy
    Value: !Sub '${DeliveryService.Name}'

