AWSTemplateFormatVersion: 2010-09-09
Description: 'API definition'

Resources :
  RestApi :
    Type : AWS::ApiGateway::RestApi
    Properties :
      Name: myApi
      Parameters:
        endpointConfigurationTypes: REGIONAL
      Body :
        openapi: 3.0.1
        info:
          title: OpenAPI definition
          version: v0
        servers:
          - url: http://internal-pn-in-appli-j6h69x8rh768-1114813573.eu-west-3.elb.amazonaws.com:8080
            description: Generated server url
        paths:
          /delivery/notifications/sent:
            get:
              tags:
                - pn-sent-notifications-controller
              operationId: searchSentNotification
              parameters:
                - name: X-PagoPA-PN-PA
                  in: header
                  required: true
                  schema:
                    type: string
                - name: startDate
                  in: query
                  required: true
                  schema:
                    type: string
                    format: date-time
                - name: endDate
                  in: query
                  required: true
                  schema:
                    type: string
                    format: date-time
                - name: recipientId
                  in: query
                  required: false
                  schema:
                    type: string
                - name: status
                  in: query
                  required: false
                  schema:
                    type: string
                    enum:
                      - RECEIVED
                      - DELIVERING
                      - DELIVERED
                      - VIEWED
                      - EFFECTIVE_DATE
                      - PAID
                      - UNREACHABLE
                - name: subjectRegExp
                  in: query
                  required: false
                  schema:
                    type: string
              responses:
                '200':
                  description: OK
                  content:
                    '*/*':
                      schema:
                        type: array
                        items:
                          $ref: '#/components/schemas/NotificationSearchRow'
        components:
          schemas:
            NotificationSearchRow:
              type: object
              properties:
                iun:
                  type: string
                paNotificationId:
                  type: string
                senderId:
                  type: string
                sentAt:
                  type: string
                  format: date-time
                subject:
                  type: string
                notificationStatus:
                  type: string
                  enum:
                    - RECEIVED
                    - DELIVERING
                    - DELIVERED
                    - VIEWED
                    - EFFECTIVE_DATE
                    - PAID
                    - UNREACHABLE
                recipientId:
                  type: string
