AWSTemplateFormatVersion: '2010-09-09'
Description: Some storage with input and output

Parameters:
  ProjectName:
    Type: String
    Description: Nome dell'ambiente destinazione

  # Unused but required by CD pipeline
  MicroserviceNumber:
    Type: Number
    Description: An unique number that identify the microservice inside the ECS cluster.

  # Unused but required by CD pipeline
  TemplateBucketBaseUrl:
    Type: String
    Description: URL da cui caricare i frammenti di template di infrastruttura

  Version:
    Type: String
    Description: 'keep track of used projects commitIds'

  CdcKinesisSourceStreamArn:
    Type: String
    Description: 'Where to send CDC'

  LogsKinesisSourceStreamArn:
    Type: String
    Description: 'Where to send Logs'

  AlarmSNSTopicName:
    Type: String
    Description: 'Topic alarm'

  LogRetention:
    Type: Number
    Default: 14

Resources:

  # Dynamo Table
  NotificationsTable:
    Type: AWS::DynamoDB::Table
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain        
    Properties:
      TableName: !Sub '${ProjectName}-Notifications'
      AttributeDefinitions:
        - AttributeName: "iun"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "iun"
          KeyType: "HASH"
      BillingMode: "PAY_PER_REQUEST"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      KinesisStreamSpecification:
        StreamArn: !Ref CdcKinesisSourceStreamArn
      StreamSpecification:
        StreamViewType: NEW_IMAGE

  NotificationsCostTable:
    Type: AWS::DynamoDB::Table
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain        
    Properties:
      TableName: !Sub '${ProjectName}-NotificationsCost'
      AttributeDefinitions:
        - AttributeName: "creditorTaxId_noticeCode"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "creditorTaxId_noticeCode"
          KeyType: "HASH"
      BillingMode: "PAY_PER_REQUEST"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true


  NotificationsQRTable:
    Type: AWS::DynamoDB::Table
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain        
    Properties:
      TableName: !Sub '${ProjectName}-NotificationsQR'
      AttributeDefinitions:
        - AttributeName: "aarQRCodeValue"
          AttributeType: "S"
        - AttributeName: "iun"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "aarQRCodeValue"
          KeyType: "HASH"
      GlobalSecondaryIndexes:
        - IndexName: "iun-index"
          KeySchema:
            - AttributeName: "iun"
              KeyType: "HASH"
          Projection:
            ProjectionType: "ALL"              
      BillingMode: "PAY_PER_REQUEST"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  NotificationsMetadataTable:
    Type: AWS::DynamoDB::Table
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain        
    Properties:
      TableName: !Sub '${ProjectName}-NotificationsMetadata'
      AttributeDefinitions:
        - AttributeName: "iun_recipientId"
          AttributeType: "S"
        - AttributeName: "sentAt"
          AttributeType: "S"
        - AttributeName: "senderId_creationMonth"
          AttributeType: "S"
        - AttributeName: "senderId_recipientId"
          AttributeType: "S"
        - AttributeName: "recipientId_creationMonth"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "iun_recipientId"
          KeyType: "HASH"
        - AttributeName: "sentAt"
          KeyType: "RANGE"
      GlobalSecondaryIndexes:
        - IndexName: "senderId"
          KeySchema:
            - AttributeName: "senderId_creationMonth"
              KeyType: "HASH"
            - AttributeName: "sentAt"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"
        - IndexName: "senderId_recipientId"
          KeySchema:
            - AttributeName: "senderId_recipientId"
              KeyType: "HASH"
            - AttributeName: "sentAt"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"
        - IndexName: "recipientId"
          KeySchema:
            - AttributeName: "recipientId_creationMonth"
              KeyType: "HASH"
            - AttributeName: "sentAt"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"
      BillingMode: "PAY_PER_REQUEST"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
  
  NotificationDelegationMetadataTable:
    Type: AWS::DynamoDB::Table
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain    
    Properties:
      TableName: !Sub '${ProjectName}-NotificationDelegationMetadata'
      AttributeDefinitions:
        - AttributeName: "iun_recipientId_delegateId_groupId"
          AttributeType: "S"
        - AttributeName: "sentAt"
          AttributeType: "S"
        - AttributeName: "delegateId_creationMonth"
          AttributeType: "S"
        - AttributeName: "delegateId_groupId_creationMonth"
          AttributeType: "S"
        - AttributeName: "mandateId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "iun_recipientId_delegateId_groupId"
          KeyType: "HASH"
        - AttributeName: "sentAt"
          KeyType: "RANGE"
      GlobalSecondaryIndexes:
        - IndexName: "delegateId"
          KeySchema:
            - AttributeName: "delegateId_creationMonth"
              KeyType: "HASH"
            - AttributeName: "sentAt"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"
        - IndexName: "delegateId_groupId"
          KeySchema:
            - AttributeName: "delegateId_groupId_creationMonth"
              KeyType: "HASH"
            - AttributeName: "sentAt"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"
        - IndexName: "mandateId"
          KeySchema:
            - AttributeName: "mandateId"
              KeyType: "HASH"
          Projection:
            ProjectionType: "ALL"
      BillingMode: "PAY_PER_REQUEST"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  ### DLQ used by lambda for communication between PN-DELIVERY and PN-DELIVERY-PUSH ###
  # NB: la coda stessa è di DLQ, quindi va allarmata. Non è necessario invece che sia allarmata la sua DLQ
  PnDeliveryInsertTriggerDLQ:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain    
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/sqs-queue.yaml"
      Parameters:
        QueueName: !Sub '${ProjectName}-delivery_insert_trigger_DLQ'
        DelaySeconds: 1
        AlarmSNSTopicName: !Ref AlarmSNSTopicName
        HasDLQ:  "false"
        OncallDLQLimit: '1'
        QueueHasAlarm:  "true"

  # Coda per inviare eventi di asseverazione, consumata da lambda per salvataggio su bucket s3
  # NB: usati i valori di default per: DelaySeconds, DeadLetterQueueName, MessageRetentionPeriod, MaxReceiveCount, DeadLetterMessageRetentionPeriod,
  # QueueOldestAgeLimit
  PnDeliveryAsseverationQueue:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain    
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/sqs-queue.yaml"
      Parameters:
        QueueName: !Sub '${ProjectName}-notificationCostServiceCalls'
        HasDLQ:  "true"
        AlarmSNSTopicName: !Ref AlarmSNSTopicName
        VisibilityTimeout: 900 # the maximum lambda timeout
        QueueHasAlarm: "false"

  PnDeliveryLogGroup:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain    
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/log-group.yaml"
      Parameters:
        LogGroupName: !Sub '${ProjectName}-delivery'
        LogsKinesisSourceStreamArn: !Ref LogsKinesisSourceStreamArn
        LogGroupRetention: !Ref LogRetention

  PnDeliveryAsseverationLogGroup:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain    
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/log-group.yaml"
      Parameters:
        LogGroupName: !Sub "${ProjectName}-delivery-asseveration-lambda"
        LogGroupPrefix: '/aws/lambda'
        LogGroupRetention: !Ref LogRetention

  PnDeliveryInsertTriggerLogGroup:
    Type: AWS::CloudFormation::Stack
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain    
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/log-group.yaml"
      Parameters:
        LogGroupName: !Sub "${ProjectName}-delivery-insert-trigger-lambda"
        LogGroupPrefix: '/aws/lambda'
        LogGroupRetention: !Ref LogRetention

Outputs:

  # Dynamo table
  NotificationsDynamoTableName:
    Description: Name of dynamodb table containing notifications
    Value: !Ref NotificationsTable
  NotificationsDynamoTableArn:
    Description: ARN of dynamodb table containing notifications
    Value: !Sub '${NotificationsTable.Arn}'
  NotificationsDynamoTableStreamArn:
    Description: ARN of dynamodb table containing stream notifications
    Value: !GetAtt NotificationsTable.StreamArn

  NotificationsCostDynamoTableName:
    Description: Name of dynamodb table containing notifications cost
    Value: !Ref NotificationsCostTable
  NotificationsCostDynamoTableArn:
    Description: ARN of dynamodb table containing notifications cost
    Value: !Sub '${NotificationsCostTable.Arn}'

  NotificationsQRDynamoTableName:
    Description: Name of dynamo table containing notifications QR
    Value: !Ref NotificationsQRTable
  NotificationsQRDynamoTableArn:
    Description: ARN of dynamodb table containing notifications QR
    Value: !Sub '${NotificationsQRTable.Arn}'

  NotificationsMetadataDynamoTableName:
    Description: Name of dynamodb table containing notifications metadata
    Value: !Ref NotificationsMetadataTable
  NotificationsMetadataDynamoTableArn:
    Description: ARN of dynamodb table containing notifications metadata
    Value: !Sub '${NotificationsMetadataTable.Arn}'

  NotificationDelegationMetadataDynamoTableName:
    Description: Name of dynamodb table containing delegated notifications metadata
    Value: !Ref NotificationDelegationMetadataTable
  NotificationDelegationMetadataDynamoTableArn:
    Description: ARN of dynamodb table containing delegated notifications metadata
    Value: !Sub '${NotificationDelegationMetadataTable.Arn}'

  # Delivery Insert Trigger DLQ
  PnDeliveryInsertTriggerDLQName:
    Value: !GetAtt PnDeliveryInsertTriggerDLQ.Outputs.QueueName
    Description: pn-delivery_insert_trigger_DLQ queue name
  PnDeliveryInsertTriggerDLQURL:
    Value: !GetAtt PnDeliveryInsertTriggerDLQ.Outputs.QueueURL
    Description: pn-delivery_insert_trigger_DLQ queue URL
  PnDeliveryInsertTriggerDLQARN:
    Value: !GetAtt PnDeliveryInsertTriggerDLQ.Outputs.QueueARN
    Description: pn-delivery_insert_trigger_DLQ queue ARN
  PnDeliveryInsertTriggerDLQAlarmARN:
    Value: !GetAtt PnDeliveryInsertTriggerDLQ.Outputs.SqsDLQAlarmArn
    Description: pn-delivery_insert_trigger_DLQ alarm ARN

  # Delivery Asseveration Queue
  PnDeliveryAsseverationQueueName:
    Value: !GetAtt PnDeliveryAsseverationQueue.Outputs.QueueName
    Description: notificationCostServiceCalls queue name
  PnDeliveryAsseverationQueueARN:
    Value: !GetAtt PnDeliveryAsseverationQueue.Outputs.QueueARN
    Description: notificationCostServiceCalls queue arn
  PnDeliveryAsseverationDLQName:
    Value: !GetAtt PnDeliveryAsseverationQueue.Outputs.DeadLetterQueueName
    Description: notificationCostServiceCalls-DLQ queue name
  PnDeliveryAsseverationDLQURL:
    Value: !GetAtt PnDeliveryAsseverationQueue.Outputs.DeadLetterQueueURL
    Description: notificationCostServiceCalls-DLQ queue url
  PnDeliveryAsseverationDLQARN:
    Value: !GetAtt PnDeliveryAsseverationQueue.Outputs.DeadLetterQueueARN
    Description: notificationCostServiceCalls-DLQ queue ARN
  PnDeliveryAsseverationDLQAlarmARN:
    Value: !GetAtt PnDeliveryAsseverationQueue.Outputs.SqsDLQAlarmArn
    Description: notificationCostServiceCalls-DLQ alarm ARN
  PnDeliveryAsseverationAgeAlarmARN:
    Value: !GetAtt PnDeliveryAsseverationQueue.Outputs.SqsAgeAlarmArn  
    Description: notificationCostServiceCalls-DLQ age alarm ARN
  
  # Log group exports
  EcsLogGroup:
    Value: !GetAtt PnDeliveryLogGroup.Outputs.LogGroupName
  PnDeliveryAsseverationLambdaName:
    Value: !Sub "${ProjectName}-delivery-asseveration-lambda"
  PnDeliveryInsertTriggerLambdaName:
    Value: !Sub "${ProjectName}-delivery-insert-trigger-lambda"

  VersioningV1V2LambdaName:
    Value: !Sub "${ProjectName}-delivery-versioning-v1v2-lambda"