AWSTemplateFormatVersion: '2010-09-09'
Description: Some storage with input and output

Parameters:
  ProjectName:
    Type: String
    Description: Nome dell'ambiente destinazione

  # Unused but required by CD pipeline
  MicroserviceNumber:
    Type: Number
    Description: An unique number that identify the microservice inside the ECS cluster.

  # Unused but required by CD pipeline
  TemplateBucketBaseUrl:
    Type: String
    Description: URL da cui caricare i frammenti di template di infrastruttura
  
  Version:
    Type: String
    Description: 'keep track of used projects commitIds'

Resources:

  ## KINESIS SOURCE STREAM FOR NOTIFICATION Change Data Capture
  NotificationCdcKinesis:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/kinesis-stream.yaml"
      Parameters:
        StreamName: !Sub '${ProjectName}-notification-cdc-stream'
        StreamRetentionPeriodHours: 24
  
  # Dynamo Table
  NotificationsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ProjectName}-Notifications'
      AttributeDefinitions:
        - AttributeName: "iun"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "iun"
          KeyType: "HASH"
      BillingMode: "PAY_PER_REQUEST"
      KinesisStreamSpecification:
        StreamArn: !GetAtt NotificationCdcKinesis.Outputs.KinesisStreamArn
      StreamSpecification: 
        StreamViewType: NEW_IMAGE

  NotificationsCostTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ProjectName}-NotificationsCost'
      AttributeDefinitions:
        - AttributeName: "creditorTaxId_noticeCode"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "creditorTaxId_noticeCode"
          KeyType: "HASH"
      BillingMode: "PAY_PER_REQUEST"

  NotificationsQRTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ProjectName}-NotificationsQR'
      AttributeDefinitions:
        - AttributeName: "aarQRCodeValue"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "aarQRCodeValue"
          KeyType: "HASH"
      BillingMode: "PAY_PER_REQUEST"

  NotificationsMetadataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ProjectName}-NotificationsMetadata'
      AttributeDefinitions:
        - AttributeName: "iun_recipientId"
          AttributeType: "S"
        - AttributeName: "sentAt"
          AttributeType: "S"
        - AttributeName: "senderId_creationMonth"
          AttributeType: "S"
        - AttributeName: "senderId_recipientId"
          AttributeType: "S"
        - AttributeName: "recipientId_creationMonth"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "iun_recipientId"
          KeyType: "HASH"
        - AttributeName: "sentAt"
          KeyType: "RANGE"
      GlobalSecondaryIndexes:
        - IndexName: "senderId"
          KeySchema:
            - AttributeName: "senderId_creationMonth"
              KeyType: "HASH"
            - AttributeName: "sentAt"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"
        - IndexName: "senderId_recipientId"
          KeySchema:
            - AttributeName: "senderId_recipientId"
              KeyType: "HASH"
            - AttributeName: "sentAt"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"
        - IndexName: "recipientId"
          KeySchema:
            - AttributeName: "recipientId_creationMonth"
              KeyType: "HASH"
            - AttributeName: "sentAt"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"
      BillingMode: "PAY_PER_REQUEST"

Outputs:
  
  # Dynamo table
  NotificationsDynamoTableName:
    Description: Name of dynamodb table containing notifications
    Value: !Ref NotificationsTable
  NotificationsDynamoTableArn:
    Description: ARN of dynamodb table containing notifications
    Value: !Sub '${NotificationsTable.Arn}'

  NotificationsCostDynamoTableName:
    Description: Name of dynamodb table containing notifications cost
    Value: !Ref NotificationsCostTable
  NotificationsCostDynamoTableArn:
    Description: ARN of dynamodb table containing notifications cost
    Value: !Sub '${NotificationsCostTable.Arn}'

  NotificationsQRDynamoTableName:
    Description: Name of dynamo table containing notifications QR
    Value: !Ref NotificationsQRTable
  NotificationsQRDynamoTableArn:
    Description: ARN of dynamodb table containing notifications QR
    Value: !Sub '${NotificationsQRTable.Arn}'

  NotificationsMetadataDynamoTableName:
    Description: Name of dynamodb table containing notifications metadata
    Value: !Ref NotificationsMetadataTable
  NotificationsMetadataDynamoTableArn:
    Description: ARN of dynamodb table containing notifications metadata
    Value: !Sub '${NotificationsMetadataTable.Arn}'

  # Notification Change Data Capture kinesis stream
  NotificationCdcKinesisStreamName:
    Value: !GetAtt NotificationCdcKinesis.Outputs.KinesisStreamName
    Description: kinesis stream name for notification dynamo table
  NotificationCdcKinesisStreamArn:
    Value: !GetAtt NotificationCdcKinesis.Outputs.KinesisStreamArn
    Description: kinesis stream Arn for notification dynamo table
  NotificationCdcKinesisKeyArn:
    Value: !GetAtt NotificationCdcKinesis.Outputs.KinesisStreamKeyArn
    Description: KMS key arn for notification stream decryption
  NotificationCdcKinesisStreamReadOnlyRoleArn:
    Value: !GetAtt NotificationCdcKinesis.Outputs.KinesisStreamReadOnlyRoleArn
    Description: KMS key arn for notification stream decryption