AWSTemplateFormatVersion: '2010-09-09'
Description: Some storage with input and output

Parameters:
  ProjectName:
    Type: String
    Description: Nome dell'ambiente destinazione

  # Unused but required by CD pipeline
  MicroserviceNumber:
    Type: Number
    Description: An unique number that identify the microservice inside the ECS cluster.

  # Unused but required by CD pipeline
  TemplateBucketBaseUrl:
    Type: String
    Description: URL da cui caricare i frammenti di template di infrastruttura

Resources:

  Keyspace:
    Type: AWS::Cassandra::Keyspace
    Properties:
      KeyspaceName: !Sub '${ProjectName}_delivery'

  AttachmentsBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      # No default retention neither legal hold.
      # Can define retention period or legal hold when upload new object or version
      ObjectLockEnabled: true
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - "*"
            AllowedMethods:
              - GET
              - PUT
              - POST
              - DELETE
              - HEAD
            AllowedOrigins:
              #- { 'Fn::ImportValue': { 'Fn::Sub':'${EnvName}-cdn-url'}}
              - "*"
            ExposedHeaders:
                - "x-amz-version-id"
  
  # Dynamo Table
  NotificationsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ProjectName}-Notifications'
      AttributeDefinitions:
        - AttributeName: "iun"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "iun"
          KeyType: "HASH"
      BillingMode: "PAY_PER_REQUEST"

  NotificationsMetadataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ProjectName}-NotificationsMetadata'
      AttributeDefinitions:
        - AttributeName: "iun_recipientId"
          AttributeType: "S"
        - AttributeName: "sentAt"
          AttributeType: "S"
        - AttributeName: "senderId_creationMonth"
          AttributeType: "S"
        - AttributeName: "senderId_recipientId"
          AttributeType: "S"
        - AttributeName: "recipientId_creationMonth"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "iun_recipientId"
          KeyType: "HASH"
        - AttributeName: "sentAt"
          KeyType: "RANGE"
      GlobalSecondaryIndexes:
        - IndexName: "senderId"
          KeySchema:
            - AttributeName: "senderId_creationMonth"
              KeyType: "HASH"
            - AttributeName: "sentAt"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"
        - IndexName: "senderId_recipientId"
          KeySchema:
            - AttributeName: "senderId_recipientId"
              KeyType: "HASH"
            - AttributeName: "sentAt"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"
        - IndexName: "recipientId"
          KeySchema:
            - AttributeName: "recipientId_creationMonth"
              KeyType: "HASH"
            - AttributeName: "sentAt"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"
      BillingMode: "PAY_PER_REQUEST"

Outputs:
  KeyspaceName:
    Description: Keyspace Name used by application to access the key-value store
    Value: !Ref Keyspace

  AttachmentsBucketName:
    Description: name of bucket going to contains notification documents
    Value: !Ref AttachmentsBucket

  AttachmentsBucketArn:
    Description: ARN of bucket going to contains notification documents
    Value: !Sub '${AttachmentsBucket.Arn}'

  # Dynamo table
  NotificationsDynamoTableName:
    Description: Name of dynamodb table containing notifications
    Value: !Ref NotificationsTable
  NotificationsDynamoTableArn:
    Description: ARN of dynamodb table containing notifications
    Value: !Sub '${NotificationsTable.Arn}'

  NotificationsMetadataDynamoTableName:
    Description: Name of dynamodb table containing notifications metadata
    Value: !Ref NotificationsMetadataTable
  NotificationsMetadataDynamoTableArn:
    Description: ARN of dynamodb table containing notifications metadata
    Value: !Sub '${NotificationsMetadataTable.Arn}'
