sequenceDiagram
    autonumber
    PG->>SeND:  GET /ext-registry/pg/v1/user-groups
    SeND-->>PG: [gruppi]
    PG->>SeND:  /delivery/notifications/delegated
    SeND-->>PG: [(iun, stato, codice_ente_mittente, [destinatario])]
    PG ->>SeND: GET /ext-registry/pa/v1/activated-on-pn
    SeND-->>PG: [codice_ente_mittente, name]

    PG ->>SeND: GET /delivery/v2.3/notifications/received/{iun}
    SeND-->>PG: Dati Notifica: [codice_ente_mittente, iun, sentAt, [identificativo_documento_alllegato(docIdx)]]<br> Storico degli stati: [ stato, elementi_di_timeline_dello_stato] <br>Destinatari: [denominazione, payment_attachmentName] <br> Timeline:[ elementId, tipo_eventp, payload_evento, timestamp_evento, [legalFactId]]  
  




    PG ->>SeND: GET /delivery/notifications/received/{iun}/attachments/documents/{docIdx}
    SeND-->>PG: url per download del documento
    PG ->>SeND: GET /delivery/notifications/received/{iun}/attachments/payment/{payment_attachmentName}
    SeND-->>PG: url per download del documento
    PG ->>SeND: GET /delivery-push/{iun}/download/legal-facts/{legalFactId}
    SeND-->>PG: url per download del documento
    Note right of SeND: Nota:  <br/> []: indica una lista 


