package it.pagopa.pn.delivery.svc.validation;

import lombok.Getter;

@Getter
public enum ErrorCodes {

	ERROR_CODE_SEND_IS_DISABLED("PN_DELIVERY_SEND_IS_DISABLED"),
	ERROR_CODE_PA_NOT_FOUND("PN_DELIVERY_PA_NOT_FOUND"),
	ERROR_CODE_INVALID_TAX_ID("PN_DELIVERY_INVALID_TAX_ID"),
	ERROR_CODE_ADDITIONAL_LANG_UNSUPPORTED_VALUE("PN_DELIVERY_ADDITIONAL_LANG_UNSUPPORTED_VALUE"),
	ERROR_CODE_ADDITIONAL_LANG_MAX_SIZE_EXCEEDED("PN_DELIVERY_ADDITIONAL_LANG_SIZE_EXCEEDED"),
	ERROR_CODE_DENOMINATION_LENGTH_EXCEEDED("PN_DELIVERY_DENOMINATION_LENGTH_EXCEEDED"),
	ERROR_CODE_DENOMINATION_INVALID_CHARACTERS("PN_DELIVERY_DENOMINATION_INVALID_CHARACTERS"),
	ERROR_CODE_MAX_ATTACHMENT("PN_DELIVERY_MAX_ATTACHMENT_NUMBER_PASSED"),
	ERROR_CODE_MAX_PAYMENT("PN_DELIVERY_MAX_PAYMENT_NUMBER_PASSED"),
	ERROR_CODE_MAX_RECIPIENT("PN_DELIVERY_MAX_RECIPIENT_NUMBER_PASSED"),
	ERROR_CODE_PAYMENT_ATTACHMENT_CONTENT_TYPE("PN_DELIVERY_PAYMENT_ATTACHMENT_CONTENT_TYPE_INVALID"),
	ERROR_CODE_PG_TAX_ID_NOT_NUMERICAL("PN_DELIVERY_PG_TAX_ID_NOT_NUMERICAL"),
	ERROR_CODE_PHYSICAL_ADDRESS_NULL("PN_DELIVERY_PHYSICAL_ADDRESS_NULL"),
	ERROR_CODE_PHYSICAL_ADDRESS_INVALID_CHARACTERS("PN_DELIVERY_PHYSICAL_ADDRESS_INVALID_CHARACTERS"),
	ERROR_CODE_PHYSICAL_ADDRESS_LENGTH_EXCEEDED("PN_DELIVERY_PHYSICAL_ADDRESS_LENGTH_EXCEEDED"),
	ERROR_CODE_PROVINCE_REQUIRED("PN_DELIVERY_PROVINCE_REQUIRED"),
	ERROR_CODE_DUPLICATED_RECIPIENT_TAX_ID("PN_DELIVERY_DUPLICATED_RECIPIENT_TAX_ID"),
	ERROR_CODE_DUPLICATED_ATTACHMENTS("PN_DELIVERY_DUPLICATED_ATTACHMENTS"),
	ERROR_CODE_INVALID_CONTEXT("PN_DELIVERY_INVALID_VALIDATION_CONTEXT");

	private final String value;

	ErrorCodes(String value) {
		this.value = value;
	}

}

